export const AppRoles = {
  admin: "admin",
  nurse : "nurse",
  pharmacy : "pharmacy",
  surgery : "surgery",
  lab : "lab",
  doctor : "doctor",
  radiology : "radiology",
  admission : "admission",
  hr : "hr",
  finance : "finance",
  staff : "staff",
  patients : "patient",
  company : "company",
  reception: "reception",
  other: "other",
}
